# Generated by Django 3.0.8 on 2021-01-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_make', models.IntegerField(default=0)),
                ('makes', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StolenVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=10)),
                ('car_color', models.CharField(max_length=10)),
                ('vin', models.CharField(max_length=17)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('make_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleMakes')),
            ],
        ),
    ]
